### ISSUE TITLE
Problems using mms.get_data() without restarting Kernel

### ISSUE THREAD

**Issue by harryclewis** [louis-richard/irfu-python#14]
Hi Louis,

I created a new virtual environment to demonstrate this issue. I'm having it on my work copy of pyrfu (2.4.1) as well as the latest version which I installed today. The problem occurs when using get_data() on local files when it has not been downloaded in the same kernel run. It throws out an exception: `AttributeError: 'NoneType' object has no attribute 'items'`.

1. Downloading the data to a local file then loading it in (1 cell in jupyter notebook)

```
from pyrfu import mms

data_path = "D://MMS"
mms.db_init(data_path)

tint = ["2017-07-11T22:33:00.000", "2017-07-11T22:34:00.000"]

mms.download_data("pdi_fpi_brst_l2", tint, 1, data_path=data_path)
result = mms.get_data("pdi_fpi_brst_l2", tint, 1, data_path=data_path)
```

2. In another cell of the same Jupyter notebook, without restarting Kernel or re-downloading:

```
result = mms.get_data("pdi_fpi_brst_l2", tint, 1, data_path=data_path)
```

Throws the AttributeError exception.

I have this issue on most of my data intervals, but some do work. Another member in my department has the same problem on her installation, even when not using previously-downloaded data.

The full error is:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], [line 1](vscode-notebook-cell:?execution_count=2&line=1)
----> [1](vscode-notebook-cell:?execution_count=2&line=1) result = mms.get_data("pdi_fpi_brst_l2", tint, 1, data_path=data_path)

File [d:\Anaconda\envs\helpingcara\lib\site-packages\pyrfu\mms\get_data.py:126], in get_data(var_str, tint, mms_id, verbose, data_path, from_sdc)
    [123] file = os.path.normpath(file_name)
    [125] if "-dist" in var["dtype"]:
--> [126]     out = dist_append(out, get_dist(file, cdf_name, tint))
    [128] else:
    [129]     out = ts_append(out, get_ts(file, cdf_name, tint))

File [d:\Anaconda\envs\helpingcara\lib\site-packages\pyrfu\mms\get_dist.py:88] in get_dist(file_path, cdf_name, tint)
     [84]file = load(file_path)
     [86]# with CDF(file_path) as file:
     [87]# Get the relevant CDF file information (zVariables)
---> [88]z_vars = [z_var[0] for z_var in file.items()]
     [90]# Get the global attributes
     [91] glob_attrs = _pycdfpp_attributes_to_dict(file.attributes)

AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by harryclewis** [comment]
Hi Louis. After some digging I've found the issue, I don't think it lies with pyrfu – local timezones are being used which led to us (UK folks) trying to pull data for which there is no burst interval.

I've closed the issue.

**Comment by louis-richard** [comment]
Hi Harry,
Thanks for bringing this up. I think it comes from the default OS timezone. The documentation of pycdfpp (https://pycdfpp.readthedocs.io/en/stable/) points this out. I will fix it by forcing the time zone to UTC in pyrfu.
