### ISSUE TITLE
pyrfu/mms/make_model_vdf.py import error

### ISSUE THREAD

**Issue by harryclewis** [louis-richard/irfu-python#2]
within the file `pyrfu/mms/make_model_vdf.py` there is an error `TypeError: 'module' object is not callable` on line 104.

I believe this is because on line 15 you are importing the module not the function within that module. When I changed line 15 to `from .rotate_tensor import rotate_tensor` it fixed the problem.

**Comment by louis-richard** [comment]
Thanks for pointing that out!! I fixed the problem.
